SamuelF2/queriesAndBatting
Jarpletz/Immaculate-Party-Time pull request #21
Opened 2024-11-30 23:28 UTC by SamuelF2

Added the Appearances model,
Added assigned queries,
Added the WAR stat calculation to batting (not 100% accurate, but it really has me stumped. Kept best attempt),
Fixed the Plate Appearance stat,
Added batting depth chart tables,
Implemented web-scraper to take questions from the grid, WAR stat calculation is a little slow, some guidance on speeding it up or getting a more accurate stat calculation would be greatly appreciated.
The new python libraries have been added to requirements.txt and may require re-installing.

2024-12-01 22:42 UTC, Jarpletz requested changes
Hey, great job! It was super cool to see it generate the correct grid from the web scrape!
I noticed a few issues:
It's getting all the correct combinations, but the questions on our grid aren't displaying in the same order as on the official site. Is this something you could look into?
When I tested it on todays grid, it did something funny, where several questions contained "Boston   Red Sox" (there are three spaces between "Boston" and "Red", which, obviously, caused it to not find a vaild team. I think this could be fixed with a bit of regex in the scraper that replaces 2+ spaces with 1 space, though it could maybe require a bit more... Could you please investigate a fix for this too?

I'll give a go at WAR myself!

2024-12-01 22:42 UTC, Jarpletz commented on Team_Roster/pages/depthChart.py
> +            # ().label("Bat"),
did you mean to remove this commented code?

2024-12-02 04:37 UTC, SamuelF2 commented
Merged the changes and the comment fix, should be good to go.

2024-12-02 22:03 UTC, Jarpletz approved these changes

2024-12-02 22:03 UTC, merged